FROM python:3.11-slim
WORKDIR /app
COPY requirements*.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-dev.txt
COPY . .
CMD ["python", "-m", "unittest", "discover", "-s", "tests"]
